### ISSUE TITLE
Unable to build spark docker image

### ISSUE THREAD

**Issue by RohitBarnwal** [met-office-lab/docker-hadoop-spark#6]
While building spark, using below commnd
docker build -t molab/spark-yarn spark

I got this error: 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by jacobtomlinson** [comment]
Hey, thanks for raising an issue! 

The repo hasn't been touched for a couple of years and we have stopped using it. Therefore we can't really provide you with any support.

Sorry!

**Comment by RohitBarnwal** [comment]
Can you point me to any repo where I can find spark cluster running in yarn mode? Thanks in advance.

**Comment by jacobtomlinson** [comment]
I'm afraid not. We are currently focusing our attention on [dask](https://github.com/dask/dask).
